print("##############################")
print("#                            #")
print("#   Muhammad Maulana Azhari  #")
print("#        2410817210003       #")
print("#                            #")
print("##############################")